/* tslint:disable */
/* eslint-disable */
/**
 * AivisSpeech Engine
 * AivisSpeech の音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AivmManifest } from './AivmManifest';
import {
    AivmManifestFromJSON,
    AivmManifestFromJSONTyped,
    AivmManifestToJSON,
} from './AivmManifest';
import type { LibrarySpeaker } from './LibrarySpeaker';
import {
    LibrarySpeakerFromJSON,
    LibrarySpeakerFromJSONTyped,
    LibrarySpeakerToJSON,
} from './LibrarySpeaker';

/**
 * AIVM (Aivis Voice Model) ファイルフォーマットの音声合成モデルの情報
 * AIVM マニフェストには音声合成モデルに関連するほぼ全てのメタデータが含まれる
 * speakers フィールド内の話者情報は、VOICEVOX ENGINE との API 互換性のため
 * AIVM マニフェストを元に Speaker / SpeakerStyle / SpeakerInfo / StyleInfo モデルに変換したもの
 * @export
 * @interface AivmInfo
 */
export interface AivmInfo {
    /**
     * 
     * @type {string}
     * @memberof AivmInfo
     */
    filePath: string;
    /**
     * 
     * @type {AivmManifest}
     * @memberof AivmInfo
     */
    manifest: AivmManifest;
    /**
     * 
     * @type {Array<LibrarySpeaker>}
     * @memberof AivmInfo
     */
    speakers: Array<LibrarySpeaker>;
}

/**
 * Check if a given object implements the AivmInfo interface.
 */
export function instanceOfAivmInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "filePath" in value;
    isInstance = isInstance && "manifest" in value;
    isInstance = isInstance && "speakers" in value;

    return isInstance;
}

export function AivmInfoFromJSON(json: any): AivmInfo {
    return AivmInfoFromJSONTyped(json, false);
}

export function AivmInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AivmInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filePath': json['file_path'],
        'manifest': AivmManifestFromJSON(json['manifest']),
        'speakers': ((json['speakers'] as Array<any>).map(LibrarySpeakerFromJSON)),
    };
}

export function AivmInfoToJSON(value?: AivmInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file_path': value.filePath,
        'manifest': AivmManifestToJSON(value.manifest),
        'speakers': ((value.speakers as Array<any>).map(LibrarySpeakerToJSON)),
    };
}

