/* tslint:disable */
/* eslint-disable */
/**
 * AivisSpeech Engine
 * AivisSpeech の音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * AIVM (Aivis Voice Model) マニフェストの話者スタイルの定義
 * @export
 * @interface AivmManifestSpeakerStyle
 */
export interface AivmManifestSpeakerStyle {
    /**
     * 
     * @type {string}
     * @memberof AivmManifestSpeakerStyle
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof AivmManifestSpeakerStyle
     */
    id: number;
}

/**
 * Check if a given object implements the AivmManifestSpeakerStyle interface.
 */
export function instanceOfAivmManifestSpeakerStyle(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function AivmManifestSpeakerStyleFromJSON(json: any): AivmManifestSpeakerStyle {
    return AivmManifestSpeakerStyleFromJSONTyped(json, false);
}

export function AivmManifestSpeakerStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AivmManifestSpeakerStyle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
    };
}

export function AivmManifestSpeakerStyleToJSON(value?: AivmManifestSpeakerStyle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
    };
}

