/* tslint:disable */
/* eslint-disable */
/**
 * AivisSpeech Engine
 * AivisSpeech の音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AivmManifestSpeakerStyle } from './AivmManifestSpeakerStyle';
import {
    AivmManifestSpeakerStyleFromJSON,
    AivmManifestSpeakerStyleFromJSONTyped,
    AivmManifestSpeakerStyleToJSON,
} from './AivmManifestSpeakerStyle';

/**
 * AIVM (Aivis Voice Model) マニフェストの話者の定義
 * 画像やボイスサンプルは容量が大きいためマニフェストには含まれず、 別途ファイルとして AIVM に格納される
 * @export
 * @interface AivmManifestSpeaker
 */
export interface AivmManifestSpeaker {
    /**
     * 
     * @type {string}
     * @memberof AivmManifestSpeaker
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AivmManifestSpeaker
     */
    supportedLanguages: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof AivmManifestSpeaker
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AivmManifestSpeaker
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof AivmManifestSpeaker
     */
    version: string;
    /**
     * 
     * @type {Array<AivmManifestSpeakerStyle>}
     * @memberof AivmManifestSpeaker
     */
    styles: Array<AivmManifestSpeakerStyle>;
}

/**
 * Check if a given object implements the AivmManifestSpeaker interface.
 */
export function instanceOfAivmManifestSpeaker(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "supportedLanguages" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "styles" in value;

    return isInstance;
}

export function AivmManifestSpeakerFromJSON(json: any): AivmManifestSpeaker {
    return AivmManifestSpeakerFromJSONTyped(json, false);
}

export function AivmManifestSpeakerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AivmManifestSpeaker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'supportedLanguages': json['supported_languages'],
        'id': json['id'],
        'uuid': json['uuid'],
        'version': json['version'],
        'styles': ((json['styles'] as Array<any>).map(AivmManifestSpeakerStyleFromJSON)),
    };
}

export function AivmManifestSpeakerToJSON(value?: AivmManifestSpeaker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'supported_languages': value.supportedLanguages,
        'id': value.id,
        'uuid': value.uuid,
        'version': value.version,
        'styles': ((value.styles as Array<any>).map(AivmManifestSpeakerStyleToJSON)),
    };
}

