/* tslint:disable */
/* eslint-disable */
/**
 * AivisSpeech Engine
 * AivisSpeech の音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * AIVM マニフェストのボイスサンプル情報 
 * @export
 * @interface AivmManifestVoiceSample
 */
export interface AivmManifestVoiceSample {
    /**
     * 
     * @type {string}
     * @memberof AivmManifestVoiceSample
     */
    audio: string;
    /**
     * 
     * @type {string}
     * @memberof AivmManifestVoiceSample
     */
    transcript: string;
}

/**
 * Check if a given object implements the AivmManifestVoiceSample interface.
 */
export function instanceOfAivmManifestVoiceSample(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "audio" in value;
    isInstance = isInstance && "transcript" in value;

    return isInstance;
}

export function AivmManifestVoiceSampleFromJSON(json: any): AivmManifestVoiceSample {
    return AivmManifestVoiceSampleFromJSONTyped(json, false);
}

export function AivmManifestVoiceSampleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AivmManifestVoiceSample {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'audio': json['audio'],
        'transcript': json['transcript'],
    };
}

export function AivmManifestVoiceSampleToJSON(value?: AivmManifestVoiceSample | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'audio': value.audio,
        'transcript': value.transcript,
    };
}

