/* tslint:disable */
/* eslint-disable */
/**
 * AivisSpeech Engine
 * AivisSpeech の音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * AIVM (Aivis Voice Model) ライブラリに関する情報
 * @export
 * @interface AivmManifest
 */
export interface AivmManifest {
    /**
     * 
     * @type {string}
     * @memberof AivmManifest
     */
    manifestVersion: string;
    /**
     * 
     * @type {string}
     * @memberof AivmManifest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AivmManifest
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof AivmManifest
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof AivmManifest
     */
    brandName: string;
    /**
     * 
     * @type {string}
     * @memberof AivmManifest
     */
    engineName: string;
    /**
     * 
     * @type {string}
     * @memberof AivmManifest
     */
    engineUuid: string;
}

/**
 * Check if a given object implements the AivmManifest interface.
 */
export function instanceOfAivmManifest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "manifestVersion" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "brandName" in value;
    isInstance = isInstance && "engineName" in value;
    isInstance = isInstance && "engineUuid" in value;

    return isInstance;
}

export function AivmManifestFromJSON(json: any): AivmManifest {
    return AivmManifestFromJSONTyped(json, false);
}

export function AivmManifestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AivmManifest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'manifestVersion': json['manifest_version'],
        'name': json['name'],
        'version': json['version'],
        'uuid': json['uuid'],
        'brandName': json['brand_name'],
        'engineName': json['engine_name'],
        'engineUuid': json['engine_uuid'],
    };
}

export function AivmManifestToJSON(value?: AivmManifest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'manifest_version': value.manifestVersion,
        'name': value.name,
        'version': value.version,
        'uuid': value.uuid,
        'brand_name': value.brandName,
        'engine_name': value.engineName,
        'engine_uuid': value.engineUuid,
    };
}

