/* tslint:disable */
/* eslint-disable */
/**
 * AivisSpeech Engine
 * AivisSpeech の音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ModelArchitecture = {
    Vits2: 'Style-Bert-VITS2',
    Vits2JpExtra: 'Style-Bert-VITS2 (JP-Extra)'
} as const;
export type ModelArchitecture = typeof ModelArchitecture[keyof typeof ModelArchitecture];


export function ModelArchitectureFromJSON(json: any): ModelArchitecture {
    return ModelArchitectureFromJSONTyped(json, false);
}

export function ModelArchitectureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelArchitecture {
    return json as ModelArchitecture;
}

export function ModelArchitectureToJSON(value?: ModelArchitecture | null): any {
    return value as any;
}

